# Generated by Django 5.1.11 on 2025-07-28 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_contact_preferences_patient_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Clinical', 'Clinical'), ('Consent', 'Consent'), ('Referral', 'Referral'), ('Lab Result', 'Lab Result'), ('Amendment', 'Amendment'), ('Other', 'Other')], max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
