# Generated by Django 5.1.11 on 2025-07-20 06:20

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_category_flag_frequency_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('nas', models.BooleanField(default=False)),
                ('questions', models.JSONField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('conditions', models.ManyToManyField(blank=True, to='core.condition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flag')),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.frequency')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CCM', 'Ccm'), ('PCM', 'Pcm'), ('BHI', 'Bhi'), ('RPM', 'Rpm')], max_length=5), blank=True, null=True, size=None)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('goals', models.JSONField(blank=True, null=True)),
                ('barriers', models.JSONField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, null=True)),
                ('interventions', models.JSONField(blank=True, null=True)),
                ('number_to_tracks', models.JSONField(blank=True, null=True)),
                ('expected_outcomes', models.JSONField(blank=True, null=True)),
                ('supports', models.JSONField(blank=True, null=True)),
                ('allergies', models.JSONField(blank=True, null=True)),
                ('medications', models.JSONField(blank=True, null=True)),
                ('conditions', models.ManyToManyField(to='core.condition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('icd_codes', models.ManyToManyField(to='core.icdcode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
