volumes:
  stage_postgres_data: {}
  stage_postgres_data_backups: {}
  stage_traefik: {}
  stage_redis_data: {}
  stage_mailpit: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: digimedix_be_stage_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: digimedix_be_stage_postgres
    volumes:
      - stage_postgres_data:/var/lib/postgresql/data
      - stage_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile-stage
    image: digimedix_be_stage_traefik
    depends_on:
      - django
    volumes:
      - stage_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  redis:
    image: docker.io/redis:6
    volumes:
      - stage_redis_data:/data


  celeryworker:
    <<: *django
    image: digimedix_be_stage_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: digimedix_be_stage_celerybeat
    command: /start-celerybeat


  mailpit:
    image: docker.io/axllent/mailpit:latest
    volumes:
      - stage_mailpit:/data
    environment:
      MP_MAX_MESSAGES: 500
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_UI_AUTH: "admin:Admin@123"
      MP_DB_FILE: /data/mailpit.db
