services:
  docs:
    image: digimedix_be_local_docs
    container_name: digimedix_be_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./digimedix_be:/app/digimedix_be:z
    ports:
      - '9000:9000'
    command: /start-docs
