volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: azura_be_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: azura_be_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  celeryworker:
    <<: *django
    image: azura_be_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: azura_be_production_celerybeat
    command: /start-celerybeat
