# Generated by Django 5.1.11 on 2025-07-14 04:57

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discipline_service', models.CharField(choices=[('Acupuncture', 'Acupuncture'), ('Administrative', 'Administrative'), ('Athletic Therapy', 'Athletic Therapy'), ('Audiology', 'Audiology'), ('Ayurveda', 'Ayurveda'), ('Chinese Medicine', 'Chinese Medicine'), ('Chiropody', 'Chiropody'), ('Chiropractic', 'Chiropractic'), ('Coaching', 'Coaching'), ('Colonics', 'Colonics'), ('Consulting', 'Consulting'), ('Counselling', 'Counselling'), ('Day Spa', 'Day Spa'), ('Dentistry', 'Dentistry'), ('Dermatology', 'Dermatology'), ('Dietetics', 'Dietetics'), ('Floating', 'Floating'), ('Foot Care Nursing', 'Foot Care Nursing'), ('Functional Medicine', 'Functional Medicine'), ('Homeopathy', 'Homeopathy'), ('IV Therapy', 'Iv Therapy'), ('Imaging', 'Imaging'), ('Kinesiology', 'Kinesiology'), ('Laser Skin + Hair', 'Laser Skin Hair'), ('Massage Therapy', 'Massage Therapy'), ('Medical - Primary Care / Family Medicine', 'Medical Primary Care'), ('Medical Aesthetics', 'Medical Aesthetics'), ('Medical Specialists', 'Medical Specialists'), ('Midwifery', 'Midwifery'), ('Naturopathic Medicine', 'Naturopathic Medicine'), ('Nutrition', 'Nutrition'), ('Occupational Therapy', 'Occupational Therapy'), ('Optometry', 'Optometry'), ('Osteopathy', 'Osteopathy'), ('Personal Training', 'Personal Training'), ('Physical Therapy', 'Physical Therapy'), ('Physiotherapy', 'Physiotherapy'), ('Pilates', 'Pilates'), ('Plastic Surgery', 'Plastic Surgery'), ('Podiatry', 'Podiatry'), ('Psychiatry', 'Psychiatry'), ('Psychology / Mental Health', 'Psychology'), ('Psychotherapy', 'Psychotherapy'), ('Reflexology', 'Reflexology'), ('Respiratory', 'Respiratory'), ('Speech Therapy', 'Speech Therapy'), ('Weight Management', 'Weight Management'), ("Women's Health", 'Womens Health'), ('Yoga', 'Yoga'), ("I can't find my discipline", 'Unknown')], max_length=60)),
                ('address', models.JSONField()),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Contact format must be one of (XXX) XXX-XXXX or XXX-XXX-XXXX', regex='^(\\([0-9]{3}\\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(unique=True)),
                ('grace_code', models.CharField(max_length=255)),
                ('web_address', models.URLField(unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
