# Generated by Django 5.1.11 on 2025-07-21 08:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='web_address',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain, e.g., example.com', regex='^([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$')]),
        ),
        migrations.CreateModel(
            name='EnabledDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain, e.g., example.com', regex='^([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
