# Generated by Django 5.1.11 on 2025-07-21 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0003_alter_businessaccount_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='web_address',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain, e.g., example.com', regex='^((localhost|\\d{1,3}(\\.\\d{1,3}){3}|([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}))(:\\d{1,5})?$')]),
        ),
        migrations.AlterField(
            model_name='enableddomain',
            name='domain',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain, e.g., example.com', regex='^((localhost|\\d{1,3}(\\.\\d{1,3}){3}|([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}))(:\\d{1,5})?$')]),
        ),
    ]
