# Generated by Django 5.1.11 on 2025-07-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0004_alter_businessaccount_web_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='initial_completed',
            field=models.BooleanField(default=False),
        ),
    ]
