# Generated by Django 5.1.11 on 2025-07-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0005_businessaccount_initial_completed'),
        ('djstripe', '0014_2_9a'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='default_stripe_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_account_cards', to='djstripe.card'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='stripe_cards',
            field=models.ManyToManyField(related_name='cards', to='djstripe.card'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='stripe_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='stripe_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='djstripe.price'),
        ),
    ]
