# Generated by Django 5.1.11 on 2025-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0006_businessaccount_default_stripe_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='communicationtemplateversion',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='communicationtemplateversion',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='enableddomain',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='enableddomain',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='smsconfiguration',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='smsconfiguration',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
    ]
