# Generated by Django 5.1.11 on 2025-07-26 08:52

import django.db.models.deletion
import timezone_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0008_alter_businessaccount_web_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('reminders', models.JSONField(blank=True, null=True)),
                ('email', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=False)),
                ('urgent_alert', models.BooleanField(default=False)),
                ('default_timezone', timezone_field.fields.TimeZoneField(blank=True, null=True)),
                ('session_timeout', models.IntegerField(default=3600)),
                ('date_format', models.CharField(blank=True, max_length=50)),
                ('audit_log_retention', models.IntegerField(default=90)),
                ('business_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business_accounts.businessaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VitalAlertConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('vital_type', models.CharField(max_length=255)),
                ('min_range', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_normal_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_normal_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_range', models.DecimalField(decimal_places=2, max_digits=6)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_alert_configurations', to='business_accounts.businessaccount')),
            ],
            options={
                'unique_together': {('business_account', 'vital_type')},
            },
        ),
    ]
