# Generated by Django 5.1.11 on 2025-07-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0009_accountconfiguration_vitalalertconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtemplate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
