# Generated by Django 5.1.11 on 2025-07-31 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_emailsms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('medicine', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('sig', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('refills', models.CharField(max_length=255)),
                ('days', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('vital_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
