# Generated by Django 5.1.11 on 2025-08-25 04:33

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status_encounter'),
        ('locations', '0005_location_type'),
        ('patients', '0007_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('vaccines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('scheduled_at', models.DateTimeField()),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number format must be one of (XXX) XXX-XXXX or XXX-XXX-XXXX', regex='^(\\([0-9]{3}\\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}$')])),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number format must be one of (XXX) XXX-XXXX or XXX-XXX-XXXX', regex='^(\\([0-9]{3}\\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}$')])),
                ('insurance_provider', models.CharField(max_length=255)),
                ('member_id', models.CharField(max_length=50)),
                ('group_number', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
