# Generated by Django 5.1.11 on 2025-07-05 12:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='provider_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='provider_groups.providergroup'),
        ),
    ]
