# Generated by Django 5.1.11 on 2025-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_groups', '0003_alter_department_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providergroup',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
