# Generated by Django 5.1.11 on 2025-08-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_groups', '0004_providergroup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='providergroup',
            name='group_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
