# Generated by Django 5.1.11 on 2025-08-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_groups', '0005_providergroup_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providergroup',
            name='group_type',
            field=models.CharField(blank=True, choices=[('Hospital System', 'Hospital System'), ('Primary Care', 'Primary Care'), ('Specialty Care', 'Specialty Care'), ('Urgent Care', 'Urgent Care')], max_length=50),
        ),
    ]
