# Generated by Django 5.1.11 on 2025-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0002_remove_user_name_user_created_at_user_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='organizations.organization'),
        ),
    ]
