# Generated by Django 5.1.11 on 2025-07-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_account_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('user', 'number')},
        ),
    ]
