# Generated by Django 5.1.11 on 2025-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_license_created_by_alter_license_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workshedule',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workshedule',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
    ]
