# Generated by Django 5.1.11 on 2025-08-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=True),
        ),
    ]
