# Generated by Django 5.1.11 on 2025-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_by_alter_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
    ]
