# Generated by Django 5.1.11 on 2025-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_created_by_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='condition',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='condition',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='cptcode',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='cptcode',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='flag',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='flag',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='hcpcscode',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='hcpcscode',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='icdcode',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='icdcode',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='loinccode',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='loinccode',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='rxcode',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='rxcode',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
    ]
