# Generated by Django 5.1.11 on 2025-07-28 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_contact_preferences_patient_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('note', models.JSONField()),
                ('note_type', models.CharField(choices=[('Phone Note', 'Phone Note'), ('Non Visit Notes', 'Non Visit Note'), ('Email Notes', 'Email'), ('Point of Care Labs', 'Point Of Care')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_visit_notes', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('visit_start_at', models.DateTimeField()),
                ('visit_end_at', models.DateTimeField()),
                ('note', models.JSONField()),
                ('note_type', models.CharField(choices=[('Simple', 'Simple'), ('SOAP', 'Soap'), ('H&p Note1', 'Hp1'), ('H&p Note2', 'Hp2'), ('H&p Note (2 column - A/P)', 'Hp Ap'), ('Pre-OP Notes', 'Pre Op')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
