# Generated by Django 5.1.11 on 2025-07-23 11:07

import django.db.models.deletion
import timezone_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_created_by_alter_location_updated_by_and_more'),
        ('patients', '0004_alter_patient_created_by_alter_patient_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_preferences',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='locations.location'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('front', models.ImageField(blank=True, null=True, upload_to='insurances/')),
                ('back', models.ImageField(blank=True, null=True, upload_to='insurances/')),
                ('relation', models.CharField(max_length=255)),
                ('carrier_name', models.CharField(max_length=255)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('group_id', models.CharField(blank=True, max_length=100)),
                ('copay', models.BooleanField(default=False)),
                ('deductible', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
