# Generated by Django 5.1.11 on 2025-07-29 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_contact_preferences_patient_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('In App', 'In App'), ('Email', 'Email'), ('SMS/Text', 'Sms Text')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
