# Generated by Django 5.1.11 on 2025-08-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_health_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_number',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
