# Generated by Django 5.1.11 on 2025-07-17 01:51

import django.core.validators
import django.db.models.deletion
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationWorkingHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('Monday', 'Mnd'), ('Tuesday', 'Tsd'), ('Wednesday', 'Wnd'), ('Thrusday', 'Td'), ('Friday', 'Frd'), ('Saturday', 'Std'), ('Sunday', 'Snd')], max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number format must be one of (XXX) XXX-XXXX or XXX-XXX-XXXX', regex='^(\\([0-9]{3}\\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}$')])),
                ('npi', models.CharField(max_length=10, unique=True)),
                ('fax', models.CharField(max_length=15, unique=True)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('note', models.TextField(blank=True)),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('physical_address', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], default='PENDING', max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
