# Generated by Django 5.1.11 on 2025-07-17 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0001_initial'),
        ('provider_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='provider_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='provider_groups.providergroup'),
        ),
        migrations.AddField(
            model_name='location',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='core.specialty'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationworkinghour',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationworkinghour',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationworkinghour',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'provider_group')},
        ),
        migrations.AlterUniqueTogether(
            name='locationworkinghour',
            unique_together={('location', 'day')},
        ),
    ]
