# Generated by Django 5.1.11 on 2025-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_created_by_alter_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='locationworkinghour',
            name='created_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='locationworkinghour',
            name='updated_by',
            field=models.PositiveBigIntegerField(blank=True, null=True, editable=False),
        ),
    ]
