# Generated by Django 5.1.11 on 2025-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_created_by_alter_location_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
