name: Azura CI Development

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on: workflow_dispatch

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # With no caching at all the entire ci process takes 5m 30s to complete!
  build-and-push-azura-be:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Stack
        run: docker compose -f docker-compose.dev.yml build

      - name: Build and push the tagged docker image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          IMAGE_TAG: development.latest
        run: |

          docker tag azura_be_dev_traefik:latest $ECR_REGISTRY/azura/traefik:$IMAGE_TAG
          docker tag azura_be_dev_celerybeat:latest $ECR_REGISTRY/azura/celerybeat:$IMAGE_TAG
          docker tag azura_be_dev_celeryworker:latest $ECR_REGISTRY/azura/celeryworker:$IMAGE_TAG
          docker tag azura_be_dev_django:latest $ECR_REGISTRY/azura/django:$IMAGE_TAG
          docker tag azura_be_dev_postgres:latest $ECR_REGISTRY/azura/postgres:$IMAGE_TAG

          docker push $ECR_REGISTRY/azura/traefik:$IMAGE_TAG
          docker push $ECR_REGISTRY/azura/celerybeat:$IMAGE_TAG
          docker push $ECR_REGISTRY/azura/celeryworker:$IMAGE_TAG
          docker push $ECR_REGISTRY/azura/django:$IMAGE_TAG
          docker push $ECR_REGISTRY/azura/postgres:$IMAGE_TAG
